parameters:
    env(REDIS_URL): redis://localhost:6379

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $projectPath: '%kernel.project_dir%'

    NumberNine\RedisBundle\:
        resource: '../../*'
        exclude:
            - '../../DependencyInjection'
            - '../../Resources'
            - '../../NumberNineRedisBundle.php'

    Redis:
        class: Redis
        calls:
            - connect:
                  - '%env(key:host:url:resolve:REDIS_URL)%'
                  - '%env(key:port:url:int:resolve:REDIS_URL)%'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'
